import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import Featured from '../components/Featured';
import Latest from '../components/Latest';
import About from '../components/About';
import BookScroller from '../components/BookScroller';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Marcereads</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to the Marcereads blog!
        </h1> */}
        <Header />

        <Featured />
        <BookScroller />

        <Latest />
        <About />

      </main>
    </div>
  )
}
